<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <GenerateProgramFile>false</GenerateProgramFile>
        <RootNamespace>Mbus.BaseParsers.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TestHelpers.fs" />
        <Compile Include="BcdParsers\ParseBcd2DigitTests.fs"/>
        <Compile Include="BcdParsers\ParseBcd4DigitTests.fs"/>
        <Compile Include="BcdParsers\ParseBcd6DigitTests.fs"/>
        <Compile Include="BcdParsers\ParseBcdU8DigitTests.fs"/>
        <Compile Include="BcdParsers\ParseBcd12DigitTests.fs"/>
        <Compile Include="BinaryParsers\TestStateHepers.fs"/>
        <Compile Include="BinaryParsers\ParseU8Tests.fs"/>
        <Compile Include="BinaryParsers\PeekU8Tests.fs"/>
        <Compile Include="BinaryParsers\ExpectU8Tests.fs"/>
        <Compile Include="BinaryParsers\ParseU16Tests.fs"/>
        <Compile Include="BinaryParsers\ParseU24Tests.fs"/>
        <Compile Include="BinaryParsers\ParseU32Tests.fs"/>
        <Compile Include="BinaryParsers\ParseU48Tests.fs"/>
        <Compile Include="BinaryParsers\ParseU64Tests.fs"/>
        <Compile Include="SkipTests.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="xunit.v3" Version="3.0.1"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all"/>
        <PackageReference Include="FsUnit.Xunit" Version="7.1.1"/>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
    </ItemGroup>

</Project>
