<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Mbus.Frames</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="CFields.fs" />
        <Compile Include="AddressParser.fs" />
        <Compile Include="AddressWriter.fs" />
        <Compile Include="Ell.fs" />
        <Compile Include="StatusField.fs" />
        <Compile Include="Tpl.fs" />
        <Compile Include="TplParser.fs" />
        <Compile Include="TplWriter.fs" />
        <Compile Include="Apl.fs" />
        <Compile Include="AplParser.fs" />
        <Compile Include="AplWriter.fs" />
        <Compile Include="Frame.fs" />
        <Compile Include="FrameParser.fs" />
        <Compile Include="FrameWriter.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Parsers\Parsers.fsproj" />
      <ProjectReference Include="..\Records\Records.fsproj" />
    </ItemGroup>

</Project>
