<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Metering.Common.Decoding.Parsers</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Compile Include="Types.fs" />
      <Compile Include="Core.fs" />
      <Compile Include="ErrorHandling.fs" />
      <Compile Include="Utility.fs" />
      <Compile Include="Fields.fs" />
      <Compile Include="Binary.fs" />
      <Compile Include="ParserRunner.fs" />
    </ItemGroup>

</Project>
