<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Metering.Mbus.Protocol</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Utility\Bcd.fs" />
        <Compile Include="Utility\BcdParsers.fs" />
        <Compile Include="Records\InfoBlock.fs" />
        <Compile Include="Records\DataInfoBlocks\Dife.fs" />
        <Compile Include="Records\DataInfoBlocks\DataField.fs" />
        <Compile Include="Records\DataInfoBlocks\FunctionField.fs" />
        <Compile Include="Records\DataInfoBlocks\StorageNumber.fs" />
        <Compile Include="Records\DataInfoBlocks\Tariff.fs" />
        <Compile Include="Records\DataInfoBlocks\SubUnit.fs" />
        <Compile Include="Records\DataInfoBlocks\Dib.fs" />
        <Compile Include="Records\ValueInfoBlocks\Utility.fs" />
        <Compile Include="Records\ValueInfoBlocks\Vif.fs" />
        <Compile Include="Records\ValueInfoBlocks\VifExtensions.fs" />
        <Compile Include="Records\ValueInfoBlocks\ActionCodes.fs" />
        <Compile Include="Records\ValueInfoBlocks\RecordErrors.fs" />
        <Compile Include="Records\ValueInfoBlocks\Vib.fs" />
        <Compile Include="Records\ValueInfoBlocks\TextVib.fs" />
        <Compile Include="Records\ValueInfoBlocks\VibRsp.fs" />
        <Compile Include="Records\ValueInfoBlocks\VibCmd.fs" />
        <Compile Include="Records\Values\Converters.fs" />
        <Compile Include="Records\Values\ValueRaw.fs" />
        <Compile Include="Records\Values\Value.fs" />
        <Compile Include="Records\RecordRaw.fs" />
        <Compile Include="Records\Record.fs" />
        <Compile Include="Frames\Protection\UnprotectionIssue.fs"/>
        <Compile Include="Frames\DeviceIdentification\IdNumber.fs" />
        <Compile Include="Frames\DeviceIdentification\Manufacturer.fs" />
        <Compile Include="Frames\DeviceIdentification\Version.fs" />
        <Compile Include="Frames\DeviceIdentification\DeviceType.fs" />
        <Compile Include="Frames\DeviceIdentification\DeviceIdentification.fs" />
        <Compile Include="Frames\CiField.fs" />
        <Compile Include="Frames\ApplicationLayer\MbusProtocol.fs" />
        <Compile Include="Frames\ApplicationLayer\AlarmProtocol.fs" />
        <Compile Include="Frames\ApplicationLayer\ApplicationResetOrSelect.fs" />
        <Compile Include="Frames\ApplicationLayer\Apl.fs" />
        <Compile Include="Frames\TransportLayer\AccessNumbers.fs" />
        <Compile Include="Frames\TransportLayer\StatusByte.fs" />
        <Compile Include="Frames\TransportLayer\ContentOfMessage.fs" />
        <Compile Include="Frames\TransportLayer\NumberOfEncryptedBlocks.fs" />
        <Compile Include="Frames\TransportLayer\Mode.fs" />
        <Compile Include="Frames\TransportLayer\ConfigurationField.fs" />
        <Compile Include="Frames\TransportLayer\DecryptionVerification.fs" />
        <Compile Include="Frames\TransportLayer\ShortHeader.fs" />
        <Compile Include="Frames\TransportLayer\LongHeader.fs" />
        <Compile Include="Frames\TransportLayer\TplHeader.fs" />
        <Compile Include="Frames\TransportLayer\AplData.fs" />
        <Compile Include="Frames\TransportLayer\Security\SecurityContext.fs" />
        <Compile Include="Frames\TransportLayer\Security\Mode5.fs" />
        <Compile Include="Frames\TransportLayer\TplWithNoneHeader.fs" />
        <Compile Include="Frames\TransportLayer\TplWithShortHeader.fs" />
        <Compile Include="Frames\TransportLayer\TplWithLongHeader.fs" />
        <Compile Include="Frames\TransportLayer\Tpl.fs" />
        <Compile Include="Frames\AuthenticationAndFragmentationLayer\Afl.fs"/>
        <Compile Include="Frames\NetworkLayer\Nwl.fs"/>
        <Compile Include="Frames\ExtendedLinkLayer\CcField.fs"/>
        <Compile Include="Frames\ExtendedLinkLayer\Ell.fs" />
        <Compile Include="Frames\DataLinkLayer\CField.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\UserData\SelectionOfDevice.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\UserData\MbusProtocol.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\UserData\LinkUserData.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\StartField.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\LField.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\AField.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\Crc.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\EndField.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\SingleCharacterFrame.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\FixedLengthFrame.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\VariableLengthFrame.fs" />
        <Compile Include="Frames\DataLinkLayer\WiredMbus\WiredMbusFrame.fs" />
        <Compile Include="Messages\MessageTypes.fs" />
        <Compile Include="Messages\RequestUserData.fs" />
        <Compile Include="Messages\PrimaryStationMessage.fs" />
        <Compile Include="Messages\ResponseUserData.fs" />
        <Compile Include="Messages\SecondaryStationMessage.fs" />
        <Compile Include="Messages\Message.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Parsers\Parsers.fsproj" />
      <ProjectReference Include="..\..\Common\Decoders\Decoders.fsproj" />
      <ProjectReference Include="..\..\Common\Security\Cryptography\Cryptography.fsproj" />
      <ProjectReference Include="..\..\Common\Utility\Utility.fsproj" />
      <ProjectReference Include="..\..\Common\Validators\Validators.fsproj" />
      <ProjectReference Include="..\PublicTypes\PublicTypes.fsproj" />
    </ItemGroup>

</Project>
