<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>ByteReaders</AssemblyName>
        <RootNamespace>Metering.Common.Decoding.ByteReaders</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Parsers\Parsers.fsproj" />
    </ItemGroup>

</Project>
