<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <GenerateProgramFile>false</GenerateProgramFile>
        <RootNamespace>Mbus.Records.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="DibTests.fs" />
        <Compile Include="RecordTests.fs" />
        <Compile Include="StorageNumTests.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="xunit.v3" Version="3.0.1"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all"/>
        <PackageReference Include="FsUnit.Xunit" Version="7.1.1"/>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Records\Records.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="Builders\RecordBuildersTests.fs" />
      <Compile Include="Builders\VibBuilderTests.fs" />
      <Compile Include="ValueInfoBlocks\RspVibTests.fs" />
      <Compile Include="ValueInfoBlocks\ParserTests.fs" />
    </ItemGroup>

</Project>
