<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="xunit.v3" Version="3.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
        <PackageReference Include="coverlet.collector" Version="6.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ByteReaders\ByteReaders.csproj" />
        <ProjectReference Include="..\Parsers\Parsers.fsproj" />
    </ItemGroup>

</Project>
